<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>13.0</LangVersion>
		<Authors>yibei333</Authors>
		<Description>基于net10.0的Web开发框架扩展.</Description>
		<Copyright>yibei333</Copyright>
		<PackageId>SharpDevFramework</PackageId>
		<PackageProjectUrl>https://github.com/yibei333/sharp-dev-framework</PackageProjectUrl>
		<PackageIcon>c-sharp.png</PackageIcon>
		<RepositoryUrl>https://github.com/yibei333/sharp-dev-framework</RepositoryUrl>
		<PackageTags>framework web aspnetcore</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Version>1.0.11</Version>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<PackageReadmeFile>nuget.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<PublishIISAssets>false</PublishIISAssets>
		<IsWebConfigTransformDisabled>true</IsWebConfigTransformDisabled>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<SatelliteResourceLanguages>zh-CN</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../../assets/c-sharp.png" Link="Assets\c-sharp.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="../../LICENSE" Link="Assets\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="../../nuget.md" Link="Assets/nuget.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" Version="10.0.11" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
		<PackageReference Include="SharpDevLib" Version="2.1.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="build\SharpDevFramework.targets">
	    <Pack>True</Pack>
	    <PackagePath>build</PackagePath>
	  </None>
	  <None Include="build\framework.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <Pack>True</Pack>
	    <PackagePath>build</PackagePath>
	  </None>
	</ItemGroup>

</Project>
